# Generated by Django 2.0.5 on 2018-06-23 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=64)),
                ('cite_key', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('volume', models.CharField(max_length=64)),
                ('number', models.IntegerField()),
                ('pages', models.CharField(max_length=64)),
                ('month', models.IntegerField()),
                ('note', models.CharField(max_length=256)),
                ('editor', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('series', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=500)),
                ('edition', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('how_published', models.CharField(max_length=500)),
                ('chapter', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=128)),
                ('booktitle', models.CharField(max_length=500)),
                ('organisation', models.CharField(max_length=500)),
                ('school', models.CharField(max_length=256)),
                ('institution', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('issn', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('urldate', models.DateField()),
                ('doi', models.CharField(max_length=500)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibman.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='bibman.UserProfile'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibman.Record'),
        ),
        migrations.AddField(
            model_name='author',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibman.Record'),
        ),
    ]
