# Generated by Django 2.0.5 on 2018-06-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='booktitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='chapter',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='cite_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='doi',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='edition',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='editor',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='how_published',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='institution',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='isbn',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='issn',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='journal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='organisation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='pages',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibman.Project'),
        ),
        migrations.AlterField(
            model_name='record',
            name='publisher',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='school',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='series',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='urldate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='volume',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
