# Generated by Django 2.0.5 on 2018-06-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibman', '0004_auto_20180623_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='edition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='isbn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
