# Generated by Django 2.0.5 on 2018-06-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibman', '0006_auto_20180623_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user',
            new_name='users',
        ),
    ]
