# Generated by Django 2.0.5 on 2018-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_title']},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='slug', unique=True),
            preserve_default=False,
        ),
    ]
