# Generated by Django 2.0.5 on 2018-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='is_reader',
            field=models.BooleanField(default=False),
        ),
    ]
