ENTRY_TYPE_CHOICES = (
    (1, _("article")),
    (2, _("book")),
    (3, _("booklet")),
    (4, _("conference")),
    (5, _("inbook")),
    (6, _("incollections")),
    (7, _("inproceedings")),
    (8, _("manual")),
    (9, _("mastersthesis")),
    (10, _("misc")),
    (11, _("phdthesis")),
    (12, _("proceedings")),
    (13, _("techreport")),
    (14, _("unpublished")),
)
