ENTRY_TYPE_CHOICES = (
    (1, "article"),
    (2, "book"),
    (3, "booklet"),
    (4, "conference"),
    (5, "inbook"),
    (6, "incollections"),
    (7, "inproceedings"),
    (8, "manual"),
    (9, "mastersthesis"),
    (10, "misc"),
    (11, "phdthesis"),
    (12, "proceedings"),
    (13, "techreport"),
    (14, "unpublished"),
)
