ENTRY_TYPE_CHOICES = (
    ('','------------'),
    ("article", "article"),
    ("book", "book"),
    ("booklet", "booklet"),
    ("conference", "conference"),
    ("inbook", "inbook"),
    ("incollections", "incollections"),
    ("inproceedings", "inproceedings"),
    ("manual", "manual"),
    ("mastersthesis", "mastersthesis"),
    ("misc", "misc"),
    ("phdthesis", "phdthesis"),
    ("proceedings", "proceedings"),
    ("techreport", "techreport"),
    ("unpublished", "unpublished"),
)
