# Generated by Django 2.0.5 on 2018-06-27 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=64)),
                ('cite_key', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('journal', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=64, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=64, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('editor', models.CharField(blank=True, max_length=256, null=True)),
                ('publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('series', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('how_published', models.CharField(blank=True, max_length=500, null=True)),
                ('chapter', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('booktitle', models.CharField(blank=True, max_length=500, null=True)),
                ('organisation', models.CharField(blank=True, max_length=500, null=True)),
                ('school', models.CharField(blank=True, max_length=256, null=True)),
                ('institution', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('issn', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('urldate', models.DateField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=500, null=True)),
                ('last_edited', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
        migrations.AddField(
            model_name='author',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
    ]
