# Generated by Django 2.0.5 on 2018-06-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='record',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='keyword',
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-cite_key']},
        ),
        migrations.RemoveField(
            model_name='record',
            name='users',
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
    ]
