# Generated by Django 2.0.5 on 2018-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20180709_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='how_published',
        ),
        migrations.RemoveField(
            model_name='record',
            name='organisation',
        ),
        migrations.AddField(
            model_name='record',
            name='annote',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='record',
            name='crossref',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='record',
            name='howpublished',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='record',
            name='key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='record',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='author',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='booktitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='cite_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='doi',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='edition',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='editor',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='isbn',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='issn',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='journal',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='month',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='school',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='series',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='urldate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
