# Generated by Django 2.0.5 on 2018-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180710_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='record',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='record',
            name='issn',
        ),
        migrations.RemoveField(
            model_name='record',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='record',
            name='url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='urldate',
        ),
        migrations.AlterField(
            model_name='record',
            name='entry_type',
            field=models.CharField(choices=[('article', 'article'), ('book', 'book'), ('booklet', 'booklet'), ('conference', 'conference'), ('inbook', 'inbook'), ('incollections', 'incollections'), ('inproceedings', 'inproceedings'), ('manual', 'manual'), ('mastersthesis', 'mastersthesis'), ('misc', 'misc'), ('phdthesis', 'phdthesis'), ('proceedings', 'proceedings'), ('techreport', 'techreport'), ('unpublished', 'unpublished')], default='article', max_length=64),
        ),
    ]
