# Generated by Django 2.0.5 on 2018-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20180710_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='edition',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='entry_type',
            field=models.CharField(choices=[('', '------------'), ('article', 'article'), ('book', 'book'), ('booklet', 'booklet'), ('conference', 'conference'), ('inbook', 'inbook'), ('incollections', 'incollections'), ('inproceedings', 'inproceedings'), ('manual', 'manual'), ('mastersthesis', 'mastersthesis'), ('misc', 'misc'), ('phdthesis', 'phdthesis'), ('proceedings', 'proceedings'), ('techreport', 'techreport'), ('unpublished', 'unpublished')], max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='month',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
