# Generated by Django 2.0.5 on 2018-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20180717_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
